import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-amber-50 text-amber-900 min-h-screen`}
      >
        {/* Header */}
        <header className="p-4 bg-amber-100 shadow-md">
          <nav className="flex justify-center gap-8">
            <a href="/" className="hover:text-amber-700">Home</a>
            <a href="/about" className="hover:text-amber-700">About</a>
            <a href="/contact" className="hover:text-amber-700">Contact</a>
            <a href="/education" className="hover:text-amber-700">Education</a>
            <a href="/hobbies" className="hover:text-amber-700">Hobbies</a>
          </nav>
        </header>

        {/* Page content */}
        <main className="p-8 max-w-4xl mx-auto">{children}</main>

        {/* Footer */}
        <footer className="text-center p-4 text-amber-800">
          &copy; {new Date().getFullYear()} My Website
        </footer>
      </body>
    </html>
  );
}
