import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
        style={{
          backgroundColor: "#f5e8c7", // light brown
          color: "#5a3e1b", // dark brown
        }}
      >
        {/* Header */}
        <header
          style={{
            backgroundColor: "#e8d3b5",
            padding: "1rem",
            boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
          }}
        >
          <nav className="flex justify-center gap-8">
            <a href="/">Home</a>
            <a href="/about">About</a>
            <a href="/contact">Contact</a>
            <a href="/education">Education</a>
            <a href="/hobbies">Hobbies</a>
          </nav>
        </header>

        <main className="p-8 max-w-4xl mx-auto">{children}</main>

        <footer
          style={{
            textAlign: "center",
            padding: "1rem",
            marginTop: "2rem",
            color: "#4a341a",
          }}
        >
          © {new Date().getFullYear()} My Website
        </footer>
      </body>
    </html>
  );
}
